#!/usr/bin/env node

import { execSync } from 'node:child_process'
import { existsSync, readFileSync, unlinkSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '..')
const envPath = resolve(root, '.env')
const templatePath = resolve(root, '.npmrc.template')
const npmrcPath = resolve(root, '.npmrc')

const originalEnvKeys = new Set(Object.keys(process.env))
const envFile = loadProjectEnv()
const CODEARTIFACT_REGISTRY = process.env.CODEARTIFACT_REGISTRY_URL
const GENERATED_MARKER = '# SDK registry routing — generated by scripts/setup-npmrc.mjs'
const BRANCH_ENV_KEYS = ['TOPBRIDGE_SDK_SOURCE_BRANCH', 'CF_PAGES_BRANCH', 'GITHUB_REF_NAME']

function loadProjectEnv() {
  const keys = new Set()

  if (!existsSync(envPath)) {
    return { exists: false, keys }
  }

  const content = readFileSync(envPath, 'utf8')

  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim()

    if (!line || line.startsWith('#')) continue

    const match = /^(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/.exec(line)
    if (!match) continue

    const [, key, rawValue] = match
    let value = rawValue.trim()

    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1)
    }

    keys.add(key)

    if (!Object.hasOwn(process.env, key)) {
      process.env[key] = value
    }
  }

  return { exists: true, keys }
}

function getCodeArtifactRegistryError() {
  if (originalEnvKeys.has('CODEARTIFACT_REGISTRY_URL')) {
    return '当前环境变量 CODEARTIFACT_REGISTRY_URL 为空，请设置有效值。'
  }

  if (!envFile.exists) {
    return '未找到 .env，请参考 .env.example 创建本地配置。'
  }

  if (!envFile.keys.has('CODEARTIFACT_REGISTRY_URL')) {
    return '.env 中缺少 CODEARTIFACT_REGISTRY_URL，请参考 .env.example 补充。'
  }

  return '.env 中 CODEARTIFACT_REGISTRY_URL 为空，请填入 CodeArtifact registry URL。'
}

function getBranch() {
  for (const key of BRANCH_ENV_KEYS) {
    const branch = normalizeBranch(process.env[key])
    if (branch) return branch
  }

  try {
    return normalizeBranch(execSync('git branch --show-current', { encoding: 'utf8' }))
  } catch {
    console.warn('[setup-npmrc] 无法检测 git 分支，默认使用公共 NPM')
    return 'main'
  }
}

function normalizeBranch(value) {
  return String(value ?? '')
    .trim()
    .replace(/^refs\/heads\//, '')
    .replace(/^origin\//, '')
}

function readExistingNpmrc() {
  return existsSync(npmrcPath) ? readFileSync(npmrcPath, 'utf8') : ''
}

function isGenerated(content) {
  return content.includes(GENERATED_MARKER)
}

const branch = getBranch()
const isDevelop = branch === 'develop'
const existingNpmrc = readExistingNpmrc()

if (!isDevelop) {
  if (existingNpmrc && isGenerated(existingNpmrc)) {
    unlinkSync(npmrcPath)
    console.log(`[setup-npmrc] 分支: ${branch} → 已删除 .npmrc，使用公共 NPM`)
  } else if (existingNpmrc) {
    console.warn(`[setup-npmrc] 分支: ${branch} → 保留非脚本生成的 .npmrc，无法强制使用公共 NPM`)
  } else {
    console.log(`[setup-npmrc] 分支: ${branch} → 不需要 .npmrc，使用公共 NPM`)
  }
  process.exit(0)
}

if (existingNpmrc && !isGenerated(existingNpmrc)) {
  console.error('[setup-npmrc] .npmrc 不是由本脚本生成的，为避免覆盖已中止')
  process.exit(1)
}

if (!CODEARTIFACT_REGISTRY) {
  console.error(
    `[setup-npmrc] develop 分支需要 CODEARTIFACT_REGISTRY_URL。${getCodeArtifactRegistryError()}`,
  )
  process.exit(1)
}

const template = readFileSync(templatePath, 'utf8')
const content = template.replace(/\{\{REGISTRY_URL\}\}/, CODEARTIFACT_REGISTRY)
writeFileSync(npmrcPath, content)
console.log(`[setup-npmrc] 分支: ${branch} → .npmrc 已指向 CodeArtifact`)
