#!/usr/bin/env node

import { execSync } from 'node:child_process'
import { readFileSync, writeFileSync, unlinkSync, existsSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '..')
const templatePath = resolve(root, '.npmrc.template')
const npmrcPath = resolve(root, '.npmrc')

const CODEARTIFACT_REGISTRY = process.env.CODEARTIFACT_REGISTRY_URL
const GENERATED_MARKER = '# SDK registry routing — generated by scripts/setup-npmrc.mjs'
const BRANCH_ENV_KEYS = ['TOPBRIDGE_SDK_SOURCE_BRANCH', 'CF_PAGES_BRANCH', 'GITHUB_REF_NAME']

function getBranch() {
  for (const key of BRANCH_ENV_KEYS) {
    const branch = normalizeBranch(process.env[key])
    if (branch) return branch
  }

  try {
    return normalizeBranch(execSync('git branch --show-current', { encoding: 'utf8' }))
  } catch {
    console.warn('[setup-npmrc] Unable to detect git branch, defaulting to NPM')
    return 'main'
  }
}

function normalizeBranch(value) {
  return String(value ?? '')
    .trim()
    .replace(/^refs\/heads\//, '')
    .replace(/^origin\//, '')
}

function readExistingNpmrc() {
  return existsSync(npmrcPath) ? readFileSync(npmrcPath, 'utf8') : ''
}

function isGenerated(content) {
  return content.includes(GENERATED_MARKER)
}

const branch = getBranch()
const isDevelop = branch === 'develop'
const existingNpmrc = readExistingNpmrc()

if (!isDevelop) {
  if (existingNpmrc && isGenerated(existingNpmrc)) {
    unlinkSync(npmrcPath)
    console.log(`[setup-npmrc] branch: ${branch} → removed .npmrc (using default NPM)`)
  } else if (existingNpmrc) {
    console.warn(
      `[setup-npmrc] branch: ${branch} → keeping non-generated .npmrc, cannot force default NPM`,
    )
  } else {
    console.log(`[setup-npmrc] branch: ${branch} → no .npmrc needed (using default NPM)`)
  }
  process.exit(0)
}

if (existingNpmrc && !isGenerated(existingNpmrc)) {
  console.error(
    '[setup-npmrc] .npmrc was not generated by this script, aborting to avoid overwriting',
  )
  process.exit(1)
}

if (!CODEARTIFACT_REGISTRY) {
  console.error(
    '[setup-npmrc] CODEARTIFACT_REGISTRY_URL is required on develop branch. See .env.example',
  )
  process.exit(1)
}

const template = readFileSync(templatePath, 'utf8')
const content = template.replace(/\{\{REGISTRY_URL\}\}/, CODEARTIFACT_REGISTRY)
writeFileSync(npmrcPath, content)
console.log(`[setup-npmrc] branch: ${branch} → .npmrc points to CodeArtifact`)
