#!/usr/bin/env node

import { execSync } from 'node:child_process'
import { existsSync, readFileSync, unlinkSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '..')
const envPath = resolve(root, '.env')
const templatePath = resolve(root, '.npmrc.template')
const npmrcPath = resolve(root, '.npmrc')

const originalEnvKeys = new Set(Object.keys(process.env))
const envFile = loadProjectEnv()
const CODEARTIFACT_REGISTRY = process.env.CODEARTIFACT_REGISTRY_URL
const GENERATED_MARKER = '# SDK registry routing — generated by scripts/setup-npmrc.mjs'
const BRANCH_ENV_KEYS = ['TOPBRIDGE_SDK_SOURCE_BRANCH', 'CF_PAGES_BRANCH', 'GITHUB_REF_NAME']

function loadProjectEnv() {
  const keys = new Set()

  if (!existsSync(envPath)) {
    return { exists: false, keys }
  }

  const content = readFileSync(envPath, 'utf8')

  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim()

    if (!line || line.startsWith('#')) continue

    const match = /^(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/.exec(line)
    if (!match) continue

    const [, key, rawValue] = match
    let value = rawValue.trim()

    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1)
    }

    keys.add(key)

    if (!Object.hasOwn(process.env, key)) {
      process.env[key] = value
    }
  }

  return { exists: true, keys }
}

function getCodeArtifactRegistryError() {
  if (originalEnvKeys.has('CODEARTIFACT_REGISTRY_URL')) {
    return 'The CODEARTIFACT_REGISTRY_URL environment variable is empty. Set a valid value.'
  }

  if (!envFile.exists) {
    return 'No .env file was found. Create local config from .env.example.'
  }

  if (!envFile.keys.has('CODEARTIFACT_REGISTRY_URL')) {
    return 'CODEARTIFACT_REGISTRY_URL is missing from .env. Add it from .env.example.'
  }

  return 'CODEARTIFACT_REGISTRY_URL is empty in .env. Set the CodeArtifact registry URL.'
}

function getBranch() {
  for (const key of BRANCH_ENV_KEYS) {
    const branch = normalizeBranch(process.env[key])
    if (branch) return branch
  }

  try {
    return normalizeBranch(execSync('git branch --show-current', { encoding: 'utf8' }))
  } catch {
    console.warn('[setup-npmrc] Unable to detect git branch. Defaulting to public npm.')
    return 'main'
  }
}

function normalizeBranch(value) {
  return String(value ?? '')
    .trim()
    .replace(/^refs\/heads\//, '')
    .replace(/^origin\//, '')
}

function readExistingNpmrc() {
  return existsSync(npmrcPath) ? readFileSync(npmrcPath, 'utf8') : ''
}

function isGenerated(content) {
  return content.includes(GENERATED_MARKER)
}

function isPnpmDevPreinstall() {
  return process.env.npm_lifecycle_event === 'pnpm:devPreinstall'
}

const branch = getBranch()
const isDevelop = branch === 'develop'
const existingNpmrc = readExistingNpmrc()

if (!isDevelop) {
  if (existingNpmrc && isGenerated(existingNpmrc)) {
    unlinkSync(npmrcPath)
    console.log(`[setup-npmrc] Branch: ${branch} -> removed .npmrc; using public npm.`)
  } else if (existingNpmrc) {
    console.warn(
      `[setup-npmrc] Branch: ${branch} -> keeping non-generated .npmrc; cannot force public npm.`,
    )
  } else {
    console.log(`[setup-npmrc] Branch: ${branch} -> no .npmrc needed; using public npm.`)
  }
  process.exit(0)
}

if (existingNpmrc && !isGenerated(existingNpmrc)) {
  console.error(
    '[setup-npmrc] .npmrc was not generated by this script. Aborting to avoid overwrite.',
  )
  process.exit(1)
}

if (!CODEARTIFACT_REGISTRY) {
  console.error(
    `[setup-npmrc] develop branch requires CODEARTIFACT_REGISTRY_URL. ${getCodeArtifactRegistryError()}`,
  )
  process.exit(1)
}

const template = readFileSync(templatePath, 'utf8')
const content = template.replace(/\{\{REGISTRY_URL\}\}/, CODEARTIFACT_REGISTRY)
const npmrcChanged = existingNpmrc !== content

if (npmrcChanged) {
  writeFileSync(npmrcPath, content)
  console.log(`[setup-npmrc] Branch: ${branch} -> .npmrc now points to CodeArtifact.`)
} else {
  console.log(`[setup-npmrc] Branch: ${branch} -> .npmrc already points to CodeArtifact.`)
}

if (npmrcChanged && isPnpmDevPreinstall()) {
  console.error(
    [
      '[setup-npmrc] The current pnpm install process has already read the old registry config.',
      '[setup-npmrc] .npmrc has been generated. Rerun pnpm install, or prefer pnpm run install:deps.',
    ].join('\n'),
  )
  process.exit(1)
}
